[package]
name = "staticlib"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.8"
wasmi = { version = "0.40.0", default-features = false }

[lib]
name = "wasmi_staticlib"
crate-type = ["staticlib"]


